language: python
python:
  - 3.7
  - 3.8
install:
  - pip install python-coveralls coverage==4.5.4  # ideally only use python-coveralls but coverage-5 broke compatiblity: https://github.com/creare-com/podpac/issues/347
  - python setup.py install
script:
  - coverage run -m unittest discover $TRAVIS_BUILD_DIR -v
after_success:
  - coveralls
